/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project2;

/**
 *
 * @author Mahaning
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeSection = new javax.swing.JPanel();
        NamePlate = new javax.swing.JLabel();
        BalancePanel = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        deactive = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        active = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        CreditCardPanel = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        CreditCardBalance = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        Loan = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        CreditCardBalance2 = new javax.swing.JLabel();
        TransactionPanel = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TransactionTableHome = new javax.swing.JTable();
        ShopPanel = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        totalamt = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        Debit = new javax.swing.JLabel();
        Credit = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NamePlate.setFont(new java.awt.Font("Noto Sans JP", 0, 24)); // NOI18N
        NamePlate.setForeground(new java.awt.Color(31, 132, 255));
        NamePlate.setText("Hello, NameHere!");

        BalancePanel.setBackground(new java.awt.Color(56, 35, 234));
        BalancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Total De-Activated Accounts :");
        BalancePanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Namm Bank");
        BalancePanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        deactive.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        deactive.setForeground(new java.awt.Color(255, 255, 255));
        deactive.setText("0");
        BalancePanel.add(deactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 30));

        jLabel44.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Total Active Account s:");
        BalancePanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel59.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Total Active Account :");
        BalancePanel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        active.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        active.setForeground(new java.awt.Color(255, 255, 255));
        active.setText("0");
        BalancePanel.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 30));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/image.png"))); // NOI18N
        BalancePanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 160));

        jLabel47.setFont(new java.awt.Font("Noto Sans JP", 2, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(153, 153, 153));
        jLabel47.setText("Welcome to Namm Bank");

        CreditCardPanel.setBackground(new java.awt.Color(56, 35, 234));
        CreditCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Todays Loan Recoverd :");
        CreditCardPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 10));

        CreditCardBalance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        CreditCardBalance.setForeground(new java.awt.Color(255, 255, 255));
        CreditCardBalance.setText("0");
        CreditCardPanel.add(CreditCardBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 20));

        jLabel49.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Total Loan Given :");
        CreditCardPanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 10));

        Loan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Loan.setForeground(new java.awt.Color(255, 255, 255));
        Loan.setText("0");
        CreditCardPanel.add(Loan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/gradient (4).png"))); // NOI18N
        CreditCardPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 160));

        CreditCardBalance2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        CreditCardBalance2.setForeground(new java.awt.Color(255, 255, 255));
        CreditCardBalance2.setText("0");
        CreditCardPanel.add(CreditCardBalance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 30));

        TransactionPanel.setBackground(new java.awt.Color(255, 255, 255));
        TransactionPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(205, 205, 205), new java.awt.Color(205, 205, 205)));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(16, 156, 202));
        jLabel52.setText("Todays Transaction");

        TransactionTableHome.setBackground(new java.awt.Color(242, 242, 242));
        TransactionTableHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TransactionTableHome.setForeground(new java.awt.Color(0, 0, 255));
        TransactionTableHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account Number", "Amount", "C/D"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TransactionTableHome.setGridColor(new java.awt.Color(220, 220, 220));
        TransactionTableHome.setRowHeight(25);
        TransactionTableHome.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TransactionTableHome);

        javax.swing.GroupLayout TransactionPanelLayout = new javax.swing.GroupLayout(TransactionPanel);
        TransactionPanel.setLayout(TransactionPanelLayout);
        TransactionPanelLayout.setHorizontalGroup(
            TransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addGroup(TransactionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TransactionPanelLayout.setVerticalGroup(
            TransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        ShopPanel.setBackground(new java.awt.Color(0, 204, 255));
        ShopPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        ShopPanel.setMinimumSize(new java.awt.Dimension(367, 191));
        ShopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Total Debited :");
        ShopPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, -1));

        jLabel57.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Namm Bank");
        ShopPanel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, 30));

        jLabel54.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Total Amount In Bank :");
        ShopPanel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        totalamt.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        totalamt.setForeground(new java.awt.Color(255, 255, 255));
        totalamt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalamt.setText("0");
        ShopPanel.add(totalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 170, -1));

        jLabel56.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Total Credited :");
        ShopPanel.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, -1));

        Debit.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        Debit.setForeground(new java.awt.Color(255, 255, 255));
        Debit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Debit.setText("0");
        ShopPanel.add(Debit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));

        Credit.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        Credit.setForeground(new java.awt.Color(255, 255, 255));
        Credit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Credit.setText("0");
        ShopPanel.add(Credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, 20));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/pinkblue1.png"))); // NOI18N

        javax.swing.GroupLayout HomeSectionLayout = new javax.swing.GroupLayout(HomeSection);
        HomeSection.setLayout(HomeSectionLayout);
        HomeSectionLayout.setHorizontalGroup(
            HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSectionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(CreditCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeSectionLayout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addGap(40, 40, 40)
                        .addComponent(ShopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TransactionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        HomeSectionLayout.setVerticalGroup(
            HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSectionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeSectionLayout.createSequentialGroup()
                        .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58))
                        .addGap(48, 48, 48)
                        .addComponent(TransactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeSectionLayout.createSequentialGroup()
                        .addComponent(NamePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addGap(77, 77, 77)
                        .addComponent(BalancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(CreditCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BalancePanel;
    private javax.swing.JLabel Credit;
    private javax.swing.JLabel CreditCardBalance;
    private javax.swing.JLabel CreditCardBalance2;
    private javax.swing.JPanel CreditCardPanel;
    private javax.swing.JLabel Debit;
    private javax.swing.JPanel HomeSection;
    private javax.swing.JLabel Loan;
    private javax.swing.JLabel NamePlate;
    private javax.swing.JPanel ShopPanel;
    private javax.swing.JPanel TransactionPanel;
    private javax.swing.JTable TransactionTableHome;
    private javax.swing.JLabel active;
    private javax.swing.JLabel deactive;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel totalamt;
    // End of variables declaration//GEN-END:variables
}
