/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import com.email.durgesh.Email;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ResetPassword extends javax.swing.JFrame {


    public Connection connect;              //Databse Connection Variable
    public  int ResetPassOtp;               // Otp variable which contains Otp generated by generateOtp() method
    public String Mail;                     // it contain email address aquire from database
    public static String ResetPassAccountNumber;   // It holds account number of user
    public ResetPassword() {
        initComponents();
//        alertText.setVisible(false);
//        OtpField.setVisible(false);
//        otpLabel.setVisible(false);
//        VerifyOtpButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AccountNumber = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        VerifyButton = new javax.swing.JButton();
        alertText = new javax.swing.JLabel();
        OtpField = new javax.swing.JTextField();
        otpLabel = new javax.swing.JLabel();
        VerifyOtpButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5));

        BackButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(153, 153, 153));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-back-arrow-30.png"))); // NOI18N
        BackButton.setText("Go Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-circled-user-male-skin-type-1-2-100 (2).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("First Check Its You");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Enter Account Number");

        AccountNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        Username.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Enter Username");

        VerifyButton.setBackground(new java.awt.Color(0, 0, 255));
        VerifyButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        VerifyButton.setForeground(new java.awt.Color(255, 255, 255));
        VerifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-search-client-30.png"))); // NOI18N
        VerifyButton.setText("Verify Details");
        VerifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyButtonActionPerformed(evt);
            }
        });

        alertText.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        alertText.setForeground(new java.awt.Color(0, 204, 51));

        OtpField.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        OtpField.setEnabled(false);
        OtpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtpFieldActionPerformed(evt);
            }
        });

        otpLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        otpLabel.setForeground(new java.awt.Color(102, 102, 102));
        otpLabel.setText("Enter OTP");

        VerifyOtpButton.setBackground(new java.awt.Color(0, 0, 255));
        VerifyOtpButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        VerifyOtpButton.setForeground(new java.awt.Color(255, 255, 255));
        VerifyOtpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-checkmark-30.png"))); // NOI18N
        VerifyOtpButton.setText("Verify OTP");
        VerifyOtpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerifyOtpButton.setEnabled(false);
        VerifyOtpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyOtpButtonActionPerformed(evt);
            }
        });

        CloseButton.setBackground(new java.awt.Color(255, 0, 0));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-close-window-30.png"))); // NOI18N
        CloseButton.setBorder(null);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackButton)
                .addGap(276, 276, 276)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(otpLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccountNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OtpField))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(VerifyButton)
                                .addGap(302, 302, 302))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(VerifyOtpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(307, 307, 307))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(alertText, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VerifyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertText)
                .addGap(37, 37, 37)
                .addComponent(otpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OtpField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VerifyOtpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    ****************************** Back Button Method ***********************************************************************
    
    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        setVisible(false);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    
//    ********************************* Username Text Field Event *************************************************************
    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    
//    --------------------------**************** Verify Button ******************----------------------------------------
    
    private void VerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyButtonActionPerformed
        
//        This try block open datatbase connection and check username and account number are avilabel in datatbase or not 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3308/namm_bank","root","root");
            String query = "Select * from logindetail where AccountNumber=? and Username=?";
            PreparedStatement pst = connect.prepareStatement(query);
            pst.setString(1, AccountNumber.getText());
            pst.setString(2, Username.getText());
            ResultSet rs = pst.executeQuery();
           
            if(rs.next()){
//                JOptionPane.showMessageDialog(null,"login sucessful !");
                ResetPassAccountNumber = AccountNumber.getText();       // Storing Account number of user
                 
//            This try block execute when above query is execute.
//            This block get Email Address of user from customer_detail Database
                try {
                   ResetPassOtp = generateOtp();
                   System.out.print(ResetPassOtp);
                   String query1 ="Select Email from customer_detail where Account_Number=?";
                   PreparedStatement pst1 = connect.prepareStatement(query1);
                   pst1.setString(1, AccountNumber.getText());
                   ResultSet rs1 = pst1.executeQuery();
                   if(rs1.next()){
                   Mail = rs1.getNString("Email"); // Storing Email into Mail Variable
                   System.out.print(Mail);
                   
//                 This Function send otp email to users email address
                   sendMail();
                   }
                   
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(null, e);
               }
           }
           else{
            JOptionPane.showMessageDialog(null,"Net Banking Account Not Found Please check details Or Call to Bank");
            AccountNumber.setText("");
            Username.setText("");
           }
           connect.close();
        } 
        catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
        }
      
    }//GEN-LAST:event_VerifyButtonActionPerformed

//    ************************************ Otp Field Event Function *********************************************
    
    private void OtpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtpFieldActionPerformed

    
//    -------------------------------****** Verify Otp Button ******-----------------------------------------------
    
//    This button check an otp  enetered  by user is valid or not
    
    private void VerifyOtpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyOtpButtonActionPerformed
        // TODO add your handling code here:

        int myotp = ResetPassOtp;
        String strOtp = Integer.toString(myotp);
        String enterOtp = OtpField.getText();
        if(strOtp.equals(enterOtp)){
           setVisible(false);
           new ChangePassword().setVisible(true);
           dispose();
        }else if("".equals(enterOtp)){

            JOptionPane.showMessageDialog(null, "Please Enter OTP!");
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Invalid Otp !");
            OtpField.setText("");
        }
    }//GEN-LAST:event_VerifyOtpButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

//    --------------------------------------------------- OTP GENERATOR METHOD ----------------------------------------------
    
    private static int generateOtp(){
    int otp = (int) (Math.random()*1000000); 
    return otp;
    }
    
//    --------------------------------------------------- SEND EMAIL MEHOD --------------------------------------------------
    
//   This Mehod Send Otp on users linked email address 
    
    private void sendMail(){
    try {
            Email email = new Email("","");    // email and password key
            email.setFrom("","Namm Bank");   // email only
            email.setSubject("Password Reset Mail");
            email.setContent("<h1>Welcome To Namm Bank</h1><p>Your Password Reset OTP is</p>"+ResetPassOtp,"text/html");
            email.addRecipient(Mail);
            email.send();
            alertText.setForeground(Color.green);
            alertText.setText("Your Account Verified SucessFully! We send OTP on Your linked Email");
     
            alertText.setVisible(true);
            OtpField.setEnabled(true);
            VerifyOtpButton.setEnabled(true);
            AccountNumber.setEnabled(false);
            Username.setEnabled(false);
            VerifyButton.setEnabled(false);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Your Account Verfied but Otp is Not Send Please Click on Verify Detail Button Again");
            alertText.setText("Your Account Verfied but Otp is Not Send Please Click on Verify Detail Button Again");
            alertText.setForeground(Color.red);
            alertText.setVisible(true);
        }
    
    
    }
    
//------------------------------------------------------- My Coding Exit Here ------------------------------------------------------------    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNumber;
    private javax.swing.JLabel BackButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField OtpField;
    private javax.swing.JTextField Username;
    private javax.swing.JButton VerifyButton;
    private javax.swing.JButton VerifyOtpButton;
    private javax.swing.JLabel alertText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel otpLabel;
    // End of variables declaration//GEN-END:variables
}
